# risklens/config.py
import os

# App Settings
APP_TITLE = "RiskLens"
APP_DESCRIPTION = "Risk & Portfolio Analytics Dashboard"
VERSION = "0.1.0"

# Defaults
DEFAULT_SYMBOLS = ["BTCUSDT", "ETHUSDT", "SOLUSDT"]
DEFAULT_TIMEFRAME = "1h"
DEFAULT_START_DATE = "2021-01-01"
DEFAULT_END_DATE = ""
DEFAULT_INITIAL_CAPITAL = 100_000.0
DEFAULT_PERIODS_PER_YEAR = 365 # Crypto
DEFAULT_ROLLING_WINDOW = 21
